import { BlogPost, CarBootSale, User } from "@/types";

type MockUser = User & {
  password: string;
};

const now = new Date().toISOString();

export const seedUsers: MockUser[] = [
  {
    id: 1,
    username: "matt",
    fullName: "Matt Duffill",
    email: "matt@example.com",
    phone: "07800 111222",
    role: "admin",
    emailConfirmed: true,
    isPremium: true,
    premiumUntil: "2027-04-08T00:00:00.000Z",
    stripeCustomerId: "cus_demo_admin",
    stripeSubscriptionId: "sub_demo_admin",
    subscriptionStatus: "active",
    subscriptionRenewsAt: "2027-04-08T00:00:00.000Z",
    lastLogin: now,
    createdAt: now,
    password: "bootsale123",
  },
  {
    id: 2,
    username: "guy",
    fullName: "Guy Harper",
    email: "guy@example.com",
    phone: "07800 333444",
    role: "admin",
    emailConfirmed: true,
    isPremium: true,
    premiumUntil: "2027-04-08T00:00:00.000Z",
    stripeCustomerId: "cus_demo_guy",
    stripeSubscriptionId: "sub_demo_guy",
    subscriptionStatus: "active",
    subscriptionRenewsAt: "2027-04-08T00:00:00.000Z",
    lastLogin: now,
    createdAt: now,
    password: "bootsale123",
  },
  {
    id: 3,
    username: "fieldandfind",
    fullName: "Field & Find Events",
    email: "organiser@example.com",
    phone: "07911 555666",
    role: "organiser",
    emailConfirmed: true,
    isPremium: true,
    premiumUntil: "2026-11-01T00:00:00.000Z",
    stripeCustomerId: "cus_demo_organiser",
    stripeSubscriptionId: "sub_demo_organiser",
    subscriptionStatus: "active",
    subscriptionRenewsAt: "2026-11-01T00:00:00.000Z",
    lastLogin: now,
    createdAt: now,
    password: "bootsale123",
  },
];

export const seedListings: CarBootSale[] = [
  {
    id: 101,
    slug: "london-holloway-field-sale",
    name: "Holloway Field Car Boot",
    teaser: "A polished North London Sunday field with a loyal crowd and fast setup.",
    location: "London",
    county: "Greater London",
    region: "South East",
    postcode: "N7 8DB",
    address: "Holloway Recreation Ground, Market Road, London",
    description:
      "Holloway Field blends regular Sunday sellers, family footfall, and a simple layout that makes the first hour count. Expect a strong mix of household finds, vintage rails, and quick breakfast queues near the entrance.",
    daysOfWeek: ["sunday"],
    nextEventDate: "2026-04-12T07:00:00.000Z",
    startTime: "07:00",
    endTime: "13:00",
    carPrice: 12,
    vanPrice: 18,
    freeParking: false,
    parkingFee: 3,
    hasCatering: true,
    petsAllowed: true,
    venueType: "outdoor",
    hasToilets: true,
    hasHotFood: true,
    hasColdDrinks: true,
    hasPicnicTables: false,
    hasIndoorStalls: false,
    hasDisabledAccess: true,
    hasRubbishBins: true,
    hasFirstAid: true,
    hasKidsActivities: false,
    otherInfo:
      "Arrive before 6:45am for the smoothest seller entry. Verified marshals direct parking and the coffee van opens before first light.",
    socialLink: "https://instagram.com/bootsalefinder",
    socialLinks: {
      instagram: "https://instagram.com/bootsalefinder",
      website: "https://carbootsale.com",
    },
    images: [
      "/assets/car-boot-homepage-hero-artem-balashevsky_1757955981240.jpg",
      "/assets/car-boot-background.jpg",
    ],
    imageAlt: "Rows of traders at a London car boot sale",
    isPremium: true,
    listingTier: "premium",
    organiserEmail: "organiser@example.com",
    organiserPhone: "07911 555666",
    organiserName: "Field & Find Events",
    showEmail: true,
    showPhone: true,
    latitude: 51.5521,
    longitude: -0.1155,
    lastReminder: now,
    isConfirmed: true,
    confirmationSent: true,
    confirmationSentAt: now,
    confirmationDue: "2026-04-10T18:00:00.000Z",
    isFeatured: true,
    isVerified: true,
    featuredRank: 1,
    viewCount: 1420,
    what3words: "boots.finder.fields",
    eventAnnouncement: "This weekend includes an extra vintage rail lane near the east entrance.",
    status: "active",
    userId: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 102,
    slug: "leeds-kirkstall-mill-yard",
    name: "Kirkstall Mill Yard Boot Sale",
    teaser: "A steady Saturday crowd with strong household clearance and regular traders.",
    location: "Leeds",
    county: "West Yorkshire",
    region: "Yorkshire",
    postcode: "LS5 3BF",
    address: "Mill Yard, Kirkstall Road, Leeds",
    description:
      "A practical Leeds site with clear parking, warm food, and enough space to browse without the usual clutter. Buyers come early for tools, records, and workshop overflow stock.",
    daysOfWeek: ["saturday"],
    nextEventDate: "2026-04-11T06:30:00.000Z",
    startTime: "06:30",
    endTime: "12:30",
    carPrice: 10,
    vanPrice: 16,
    freeParking: true,
    parkingFee: null,
    hasCatering: true,
    petsAllowed: true,
    venueType: "outdoor",
    hasToilets: true,
    hasHotFood: true,
    hasColdDrinks: true,
    hasPicnicTables: true,
    hasIndoorStalls: false,
    hasDisabledAccess: true,
    hasRubbishBins: true,
    hasFirstAid: false,
    hasKidsActivities: false,
    otherInfo:
      "The sheltered wall along the north edge is popular in windy weather and the bacon van is usually trading from 6am.",
    socialLink: "https://facebook.com/bootsalefinder",
    socialLinks: {
      facebook: "https://facebook.com/bootsalefinder",
    },
    images: ["/assets/carboot2_1757961041589.png"],
    imageAlt: "Leeds buyers browsing tables and rails",
    isPremium: true,
    listingTier: "premium",
    organiserEmail: "organiser@example.com",
    organiserPhone: "07911 555666",
    organiserName: "Field & Find Events",
    showEmail: true,
    showPhone: true,
    latitude: 53.8165,
    longitude: -1.5865,
    lastReminder: now,
    isConfirmed: true,
    confirmationSent: true,
    confirmationSentAt: now,
    confirmationDue: "2026-04-10T17:00:00.000Z",
    isFeatured: true,
    isVerified: true,
    featuredRank: 2,
    viewCount: 980,
    what3words: "stalls.buyer.mill",
    eventAnnouncement: "Fresh tools and garden stock expected this weekend.",
    status: "active",
    userId: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 103,
    slug: "bristol-downs-early-bird",
    name: "The Downs Early Bird Boot Sale",
    teaser: "A bright, open Sunday market with a strong cafe corner and premium profile.",
    location: "Bristol",
    county: "Bristol",
    region: "South West",
    postcode: "BS9 1FG",
    address: "The Downs, Stoke Road, Bristol",
    description:
      "A polished outdoor sale with good city access, easy browsing lanes, and a reliable mix of household clearances, collectibles, and local makers.",
    daysOfWeek: ["sunday"],
    nextEventDate: "2026-04-12T07:15:00.000Z",
    startTime: "07:15",
    endTime: "13:15",
    carPrice: 11,
    vanPrice: 17,
    freeParking: true,
    parkingFee: null,
    hasCatering: true,
    petsAllowed: true,
    venueType: "outdoor",
    hasToilets: true,
    hasHotFood: true,
    hasColdDrinks: true,
    hasPicnicTables: true,
    hasIndoorStalls: false,
    hasDisabledAccess: true,
    hasRubbishBins: true,
    hasFirstAid: true,
    hasKidsActivities: true,
    otherInfo:
      "Family-friendly and well marshalled. The organiser sends reminder emails on Fridays to keep the event status fresh.",
    socialLink: "https://carbootsale.com",
    socialLinks: {
      website: "https://carbootsale.com",
      instagram: "https://instagram.com/bootsalefinder",
    },
    images: [
      "/assets/car-boot-background.jpg",
      "/assets/car-boot-homepage-hero-artem-balashevsky_1757955981240.jpg",
    ],
    imageAlt: "Bristol field with early-morning traders",
    isPremium: true,
    listingTier: "premium",
    organiserEmail: "events@downsboot.co.uk",
    organiserPhone: "07710 222333",
    organiserName: "Downs Weekend Markets",
    showEmail: true,
    showPhone: true,
    latitude: 51.4604,
    longitude: -2.6219,
    lastReminder: now,
    isConfirmed: true,
    confirmationSent: true,
    confirmationSentAt: now,
    confirmationDue: "2026-04-10T19:00:00.000Z",
    isFeatured: true,
    isVerified: true,
    featuredRank: 3,
    viewCount: 861,
    what3words: "downs.market.early",
    eventAnnouncement: "Weather outlook looks dry through mid-morning.",
    status: "active",
    userId: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 104,
    slug: "chesterfield-indoor-outdoor-trade",
    name: "Chesterfield Indoor & Outdoor Trade Yard",
    teaser: "A practical all-weather mix of shed stock, general bric-a-brac, and indoor backup.",
    location: "Chesterfield",
    county: "Derbyshire",
    region: "East Midlands",
    postcode: "S41 9QX",
    address: "Trade Yard, Brimington Road, Chesterfield",
    description:
      "A dependable sale for mixed weather with both covered and open space. Buyers come for DIY stock, furniture clearances, and everyday finds.",
    daysOfWeek: ["saturday"],
    nextEventDate: "2026-04-11T07:00:00.000Z",
    startTime: "07:00",
    endTime: "12:00",
    carPrice: 9,
    vanPrice: 15,
    freeParking: true,
    parkingFee: null,
    hasCatering: false,
    petsAllowed: false,
    venueType: "mixed",
    hasToilets: true,
    hasHotFood: false,
    hasColdDrinks: true,
    hasPicnicTables: false,
    hasIndoorStalls: true,
    hasDisabledAccess: true,
    hasRubbishBins: true,
    hasFirstAid: false,
    hasKidsActivities: false,
    otherInfo:
      "Free tier example. Core details are visible, while richer gallery and social promotion are reserved for premium listings.",
    socialLink: null,
    socialLinks: null,
    images: ["/car-boot-sale.jpg"],
    imageAlt: "Indoor and outdoor trade yard",
    isPremium: false,
    listingTier: "free",
    organiserEmail: "admin@tradeyardboots.co.uk",
    organiserPhone: "01246 111222",
    organiserName: "Trade Yard Boot Sales",
    showEmail: false,
    showPhone: true,
    latitude: 53.2515,
    longitude: -1.4143,
    lastReminder: now,
    isConfirmed: true,
    confirmationSent: true,
    confirmationSentAt: now,
    confirmationDue: "2026-04-10T18:00:00.000Z",
    isFeatured: false,
    isVerified: false,
    featuredRank: null,
    viewCount: 402,
    what3words: null,
    eventAnnouncement: null,
    status: "active",
    userId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 105,
    slug: "newcastle-quayside-bargain-morning",
    name: "Quayside Bargain Morning",
    teaser: "A riverside urban boot sale with antiques, records, and specialist stalls.",
    location: "Newcastle",
    county: "Tyne and Wear",
    region: "North East",
    postcode: "NE1 3DE",
    address: "Quayside Events Yard, Newcastle upon Tyne",
    description:
      "A curated-feeling city sale with strong specialist stock, a clean layout, and an organiser who updates the status every week.",
    daysOfWeek: ["sunday"],
    nextEventDate: "2026-04-12T08:00:00.000Z",
    startTime: "08:00",
    endTime: "13:30",
    carPrice: 14,
    vanPrice: 22,
    freeParking: false,
    parkingFee: 4,
    hasCatering: true,
    petsAllowed: true,
    venueType: "outdoor",
    hasToilets: true,
    hasHotFood: true,
    hasColdDrinks: true,
    hasPicnicTables: true,
    hasIndoorStalls: false,
    hasDisabledAccess: true,
    hasRubbishBins: true,
    hasFirstAid: true,
    hasKidsActivities: false,
    otherInfo:
      "Premium subscribers can add event announcements and social links to help regular buyers plan repeat visits.",
    socialLink: "https://quaysidebargains.co.uk",
    socialLinks: {
      website: "https://quaysidebargains.co.uk",
      facebook: "https://facebook.com/bootsalefinder",
    },
    images: ["/assets/car-boot-background.jpg"],
    imageAlt: "Newcastle riverside sale",
    isPremium: true,
    listingTier: "premium",
    organiserEmail: "hello@quaysidebargains.co.uk",
    organiserPhone: "0191 700 2222",
    organiserName: "Quayside Events",
    showEmail: true,
    showPhone: true,
    latitude: 54.9690,
    longitude: -1.6078,
    lastReminder: now,
    isConfirmed: true,
    confirmationSent: true,
    confirmationSentAt: now,
    confirmationDue: "2026-04-10T18:30:00.000Z",
    isFeatured: false,
    isVerified: true,
    featuredRank: null,
    viewCount: 633,
    what3words: "quay.finds.market",
    eventAnnouncement: "Record dealers return this Sunday.",
    status: "active",
    userId: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 106,
    slug: "norwich-farm-gate-boot-sale",
    name: "Farm Gate Boot Sale",
    teaser: "Open-air Norfolk browsing with easy parking, produce, and broad family appeal.",
    location: "Norwich",
    county: "Norfolk",
    region: "East of England",
    postcode: "NR10 4EA",
    address: "Farm Gate Field, Reepham Road, Norwich",
    description:
      "A traditional field sale with space, good seller access, and a quieter pace for buyers who want furniture, tools, and household bargains.",
    daysOfWeek: ["saturday"],
    nextEventDate: "2026-04-11T07:30:00.000Z",
    startTime: "07:30",
    endTime: "12:30",
    carPrice: 8,
    vanPrice: 14,
    freeParking: true,
    parkingFee: null,
    hasCatering: true,
    petsAllowed: true,
    venueType: "outdoor",
    hasToilets: true,
    hasHotFood: true,
    hasColdDrinks: true,
    hasPicnicTables: true,
    hasIndoorStalls: false,
    hasDisabledAccess: false,
    hasRubbishBins: true,
    hasFirstAid: false,
    hasKidsActivities: true,
    otherInfo:
      "Buyers like the farm shop corner and the clear access lanes. Great example of a high-quality verified countryside listing.",
    socialLink: null,
    socialLinks: null,
    images: ["/assets/carboot2_1757961041589.png"],
    imageAlt: "Norfolk field sale at sunrise",
    isPremium: false,
    listingTier: "free",
    organiserEmail: "hello@farmgateboots.co.uk",
    organiserPhone: "01603 123456",
    organiserName: "Farm Gate Markets",
    showEmail: true,
    showPhone: true,
    latitude: 52.6733,
    longitude: 1.2033,
    lastReminder: null,
    isConfirmed: true,
    confirmationSent: false,
    confirmationSentAt: null,
    confirmationDue: "2026-04-10T17:00:00.000Z",
    isFeatured: false,
    isVerified: true,
    featuredRank: null,
    viewCount: 287,
    what3words: null,
    eventAnnouncement: null,
    status: "active",
    userId: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const seedBlogPosts: BlogPost[] = [
  {
    id: 1,
    slug: "what-makes-a-trustworthy-car-boot-sale-listing",
    title: "What Makes a Trustworthy Car Boot Sale Listing?",
    excerpt:
      "Why verified organisers, fresh reminders, and clear practical details matter more than endless ad slots.",
    category: "Trust & Listings",
    readingTime: "5 min read",
    publishedAt: "2026-04-08",
    seoDescription:
      "Learn why verified organiser details, practical amenities, and regular confirmation reminders create a better car boot sale directory.",
    heroImage: "/assets/car-boot-homepage-hero-artem-balashevsky_1757955981240.jpg",
    relatedListingSlugs: ["london-holloway-field-sale", "bristol-downs-early-bird"],
    content: [
      "The best car boot directories do not just list events. They tell buyers whether a sale still feels alive, organised, and worth the petrol.",
      "Every premium listing is designed to surface the details people actually need: when to arrive, what the parking looks like, whether there are toilets, and whether the organiser still confirms the event week to week.",
      "That combination of verification, reminders, and clearer design is what turns a directory into something you can trust before sunrise.",
    ],
  },
  {
    id: 2,
    slug: "how-to-price-your-stall-for-a-busy-saturday",
    title: "How to Price Your Stall for a Busy Saturday",
    excerpt:
      "A quick organiser guide to balancing car, van, and premium placement prices without scaring off regular sellers.",
    category: "Organiser Advice",
    readingTime: "4 min read",
    publishedAt: "2026-04-07",
    seoDescription:
      "Simple pricing advice for organisers who want healthy seller turnout, strong early bookings, and a fair premium listing pitch.",
    heroImage: "/assets/carboot2_1757961041589.png",
    relatedListingSlugs: ["leeds-kirkstall-mill-yard"],
    content: [
      "The strongest Saturday sales tend to keep pricing predictable. Car sellers want to know the cost early and feel the value in the footfall, layout, and organisation around them.",
      "Premium visibility should feel like an upgrade to the listing itself, not a tax on sellers. Better imagery, verified trust signals, and richer updates are easier to defend than vague promises.",
      "Keep the basics clear, then use premium features to deepen quality rather than clutter the listing.",
    ],
  },
  {
    id: 3,
    slug: "what-to-check-before-you-drive-to-a-boot-sale",
    title: "What to Check Before You Drive to a Boot Sale",
    excerpt:
      "A buyer-friendly checklist covering weather, parking, timings, and the details that usually get buried on older sites.",
    category: "Buyer Tips",
    readingTime: "6 min read",
    publishedAt: "2026-04-06",
    seoDescription:
      "Check the weather, parking, timings, and organiser updates before you travel to a car boot sale anywhere in the UK.",
    heroImage: "/assets/car-boot-background.jpg",
    relatedListingSlugs: ["newcastle-quayside-bargain-morning", "norwich-farm-gate-boot-sale"],
    content: [
      "Before you set off, check the next event time, the organiser update, and whether parking is included or paid. Those three points save most wasted trips.",
      "If the event is outdoors, morning weather matters more than the all-day summary. Dry early hours can still make for a strong boot sale even if showers arrive later.",
      "The best listings also tell you whether the site is accessible, has refreshments, and offers indoor fallback space. Those details change whether a trip feels worth it.",
    ],
  },
];
